# Projekt 1 — Analiza napiwków w restauracji

## Wstęp do eksploracji danych w Pythonie

W projekcie wykorzystamy zbiór **`tips`** dostępny w bibliotece Seaborn.

### Cele
Po wykonaniu projektu będziesz potrafić:
- wczytać i obejrzeć zbiór danych,
- rozpoznawać podstawowe typy zmiennych,
- wybierać kolumny i obserwacje,
- filtrować i sortować dane,
- tworzyć nowe zmienne,
- obliczać statystyki opisowe,
- korzystać z `value_counts()`, `crosstab()` i `groupby()`,
- tworzyć podstawowe wizualizacje,
- formułować proste wnioski z eksploracyjnej analizy danych.

> Jedna obserwacja w zbiorze odpowiada jednemu rachunkowi w restauracji.

## Opis zmiennych

| Zmienna | Znaczenie |
|---|---|
| `total_bill` | wartość rachunku |
| `tip` | napiwek |
| `sex` | płeć osoby płacącej |
| `smoker` | informacja, czy klient pali |
| `day` | dzień tygodnia |
| `time` | pora posiłku: lunch lub kolacja |
| `size` | liczba osób przy stoliku |

## 0. Przygotowanie środowiska

Zaimportuj biblioteki `pandas`, `numpy`, `matplotlib.pyplot` oraz `seaborn`. Następnie wczytaj zbiór `tips` do obiektu `df`.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = sns.load_dataset("tips")

## 1. Pierwsze spojrzenie na dane

**Zadanie 1.** Wyświetl pierwszych 5 oraz ostatnich 5 obserwacji. Następnie sprawdź liczbę wierszy i kolumn oraz nazwy wszystkich kolumn.

In [48]:
# Wpisz rozwiązanie tutaj
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

Ostatnie 5 obserwacji:

In [49]:
# Wpisz rozwiązanie tutaj
df.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

Wymiary zbioru:

In [52]:
# Wpisz rozwiązanie tutaj
print(df)

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

Nazwy kolumn:

In [53]:
# Wpisz rozwiązanie tutaj
df.head(0)

Empty DataFrame
Columns: [total_bill, tip, sex, smoker, day, time, size]
Index: []

## 2. Struktura i typy danych

**Zadanie 2.** Wyświetl informacje o zbiorze. Określ typy zmiennych i sprawdź, czy występują braki danych.

In [60]:
# Wpisz rozwiązanie tutaj
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

Typy danych:

In [68]:
# Wpisz rozwiązanie tutaj
df.dtypes

total_bill     float64
tip            float64
sex           category
smoker        category
day           category
time          category
size             int64
dtype: object

Liczba braków w każdej kolumnie:

In [72]:
# Wpisz rozwiązanie tutaj
df.isna()

     total_bill    tip    sex  smoker    day   time   size
0         False  False  False   False  False  False  False
1         False  False  False   False  False  False  False
2         False  False  False   False  False  False  False
3         False  False  False   False  False  False  False
4         False  False  False   False  False  False  False
..          ...    ...    ...     ...    ...    ...    ...
239       False  False  False   False  False  False  False
240       False  False  False   False  False  False  False
241       False  False  False   False  False  False  False
242       False  False  False   False  False  False  False
243       False  False  False   False  False  False  False

[244 rows x 7 columns]

Sprawdź dostępne kategorie dla zmiennej `day`.

In [80]:
# Wpisz rozwiązanie tutaj
df["day"]

0       Sun
1       Sun
2       Sun
3       Sun
4       Sun
       ...
239     Sat
240     Sat
241     Sat
242     Sat
243    Thur
Name: day, Length: 244, dtype: category
Categories (4, str): ['Thur', 'Fri', 'Sat', 'Sun']

## 3. Wybieranie kolumn i obserwacji

**Zadanie 3.** Wyświetl kolumnę `total_bill`, a następnie kolumny `total_bill` i `tip`. Sprawdź typ obu wyników.

In [74]:
# Wpisz rozwiązanie tutaj
df["total_bill"]

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [81]:
# Wpisz rozwiązanie tutaj
df["tip"]

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ...
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

In [86]:
# Wpisz rozwiązanie tutaj
df[["total_bill", "tip"]]

     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

**Zadanie 4.** Wyświetl pierwszych 10 obserwacji, ale tylko kolumny `total_bill`, `tip` oraz `day`, używając `loc`.

In [96]:
# Wpisz rozwiązanie tutaj

df.loc[0:9, ("total_bill", "tip", "day")]

   total_bill   tip  day
0       16.99  1.01  Sun
1       10.34  1.66  Sun
2       21.01  3.50  Sun
3       23.68  3.31  Sun
4       24.59  3.61  Sun
5       25.29  4.71  Sun
6        8.77  2.00  Sun
7       26.88  3.12  Sun
8       15.04  1.96  Sun
9       14.78  3.23  Sun

Wykonaj analogiczne zadanie za pomocą `iloc`.

In [102]:
# Wpisz rozwiązanie tutaj
df.iloc[0:10, [0, 1, 4]]

   total_bill   tip  day
0       16.99  1.01  Sun
1       10.34  1.66  Sun
2       21.01  3.50  Sun
3       23.68  3.31  Sun
4       24.59  3.61  Sun
5       25.29  4.71  Sun
6        8.77  2.00  Sun
7       26.88  3.12  Sun
8       15.04  1.96  Sun
9       14.78  3.23  Sun

## 4. Statystyki opisowe

**Zadanie 5.** Wyznacz podstawowe statystyki opisowe zmiennych numerycznych.

In [103]:
# Wpisz rozwiązanie tutaj
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

**Zadanie 6.** Oblicz średnią i medianę dla wartości rachunku oraz napiwku.

In [117]:
# Wpisz rozwiązanie tutaj
df[["total_bill", "tip"]].mean()

total_bill    19.785943
tip            2.998279
dtype: float64

In [116]:
# Wpisz rozwiązanie tutaj
df[["total_bill", "tip"]].median()

total_bill    17.795
tip            2.900
dtype: float64

Sprawdź minimum, maksimum i odchylenie standardowe wartości rachunku.

In [119]:
# Wpisz rozwiązanie tutaj
print(df[["total_bill", "tip"]].min())
print(df[["total_bill", "tip"]].max())
print(df[["total_bill", "tip"]].std())

total_bill    3.07
tip           1.00
dtype: float64
total_bill    50.81
tip           10.00
dtype: float64
total_bill    8.902412
tip           1.383638
dtype: float64

## 5. Filtrowanie danych

**Zadanie 7.** Znajdź wszystkie rachunki przekraczające 40 dolarów.

In [131]:
# Wpisz rozwiązanie tutaj
df[df["total_bill"] > 40]

     total_bill    tip     sex smoker   day    time  size
59        48.27   6.73    Male     No   Sat  Dinner     4
95        40.17   4.73    Male    Yes   Fri  Dinner     4
102       44.30   2.50  Female    Yes   Sat  Dinner     3
142       41.19   5.00    Male     No  Thur   Lunch     5
156       48.17   5.00    Male     No   Sun  Dinner     6
170       50.81  10.00    Male    Yes   Sat  Dinner     3
182       45.35   3.50    Male    Yes   Sun  Dinner     3
184       40.55   3.00    Male    Yes   Sun  Dinner     2
197       43.11   5.00  Female    Yes  Thur   Lunch     4
212       48.33   9.00    Male     No   Sat  Dinner     4

**Zadanie 8.** Znajdź rachunki przekraczające 40 dolarów, dla których napiwek przekroczył 5 dolarów.

In [133]:
# Wpisz rozwiązanie tutaj
df[(df["total_bill"] > 40) & (df["tip"] > 5)]

     total_bill    tip   sex smoker  day    time  size
59        48.27   6.73  Male     No  Sat  Dinner     4
170       50.81  10.00  Male    Yes  Sat  Dinner     3
212       48.33   9.00  Male     No  Sat  Dinner     4

**Zadanie 9.** Znajdź wszystkie obserwacje dotyczące kolacji w sobotę lub niedzielę.

In [138]:
# Wpisz rozwiązanie tutaj 
df[((df["day"] == "Sun") | (df["day"] == "Sat")) & (df["time"] == "Dinner")]

     total_bill   tip     sex smoker  day    time  size
0         16.99  1.01  Female     No  Sun  Dinner     2
1         10.34  1.66    Male     No  Sun  Dinner     3
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
238       35.83  4.67  Female     No  Sat  Dinner     3
239       29.03  5.92    Male     No  Sat  Dinner     3
240       27.18  2.00  Female    Yes  Sat  Dinner     2
241       22.67  2.00    Male    Yes  Sat  Dinner     2
242       17.82  1.75    Male     No  Sat  Dinner     2

[163 rows x 7 columns]

## 6. Sortowanie

**Zadanie 10.** Znajdź 10 największych rachunków.

In [149]:
# Wpisz rozwiązanie tutaj
df2 = df.sort_values("total_bill", ascending = False)
df2. head(10)

     total_bill    tip     sex smoker   day    time  size
170       50.81  10.00    Male    Yes   Sat  Dinner     3
212       48.33   9.00    Male     No   Sat  Dinner     4
59        48.27   6.73    Male     No   Sat  Dinner     4
156       48.17   5.00    Male     No   Sun  Dinner     6
182       45.35   3.50    Male    Yes   Sun  Dinner     3
102       44.30   2.50  Female    Yes   Sat  Dinner     3
197       43.11   5.00  Female    Yes  Thur   Lunch     4
142       41.19   5.00    Male     No  Thur   Lunch     5
184       40.55   3.00    Male    Yes   Sun  Dinner     2
95        40.17   4.73    Male    Yes   Fri  Dinner     4

**Zadanie 11.** Znajdź 10 największych napiwków.

In [150]:
# Wpisz rozwiązanie tutaj
df3 = df.sort_values("tip", ascending = False)
df3. head(10)

     total_bill    tip     sex smoker   day    time  size
170       50.81  10.00    Male    Yes   Sat  Dinner     3
212       48.33   9.00    Male     No   Sat  Dinner     4
23        39.42   7.58    Male     No   Sat  Dinner     4
59        48.27   6.73    Male     No   Sat  Dinner     4
141       34.30   6.70    Male     No  Thur   Lunch     6
183       23.17   6.50    Male    Yes   Sun  Dinner     4
214       28.17   6.50  Female    Yes   Sat  Dinner     3
47        32.40   6.00    Male     No   Sun  Dinner     4
239       29.03   5.92    Male     No   Sat  Dinner     3
88        24.71   5.85    Male     No  Thur   Lunch     2

## 7. Tworzenie nowej zmiennej

**Zadanie 12.** Utwórz zmienną `tip_pct`, określającą napiwek jako procent wartości rachunku. Wyświetl pierwsze obserwacje.

In [153]:
# Wpisz rozwiązanie tutaj
tip_pct = (df["tip"]/df["total_bill"])*100
tip_pct

0       5.944673
1      16.054159
2      16.658734
3      13.978041
4      14.680765
         ...
239    20.392697
240     7.358352
241     8.822232
242     9.820426
243    15.974441
Length: 244, dtype: float64

**Zadanie 13.** Oblicz średnią i medianę procentowego napiwku.

In [25]:
# Wpisz rozwiązanie tutaj

## 8. Liczebności kategorii

**Zadanie 14.** Sprawdź liczbę rachunków w każdym dniu tygodnia, a następnie liczebności dla `time` i `sex`.

In [26]:
# Wpisz rozwiązanie tutaj

In [27]:
# Wpisz rozwiązanie tutaj

In [28]:
# Wpisz rozwiązanie tutaj

## 9. Tabele krzyżowe

**Zadanie 15.** Utwórz tabelę pokazującą liczbę rachunków w poszczególnych dniach z podziałem na lunch i kolację. Dodaj sumy brzegowe.

In [29]:
# Wpisz rozwiązanie tutaj

## 10. Grupowanie danych

**Zadanie 16.** Oblicz średni rachunek dla każdego dnia tygodnia.

In [30]:
# Wpisz rozwiązanie tutaj

**Zadanie 17.** Oblicz średni rachunek i średni napiwek dla każdego dnia.

In [31]:
# Wpisz rozwiązanie tutaj

**Zadanie 18.** Oblicz średni procentowy napiwek w zależności od dnia i pory posiłku.

In [32]:
# Wpisz rozwiązanie tutaj

## 11. Rozkład wartości rachunków

**Zadanie 19.** Przedstaw rozkład wartości rachunków za pomocą histogramu z estymatą KDE.

In [33]:
# Wpisz rozwiązanie tutaj

## 12. Zależność między rachunkiem a napiwkiem

**Zadanie 20.** Utwórz wykres punktowy przedstawiający zależność między wartością rachunku a napiwkiem.

In [34]:
# Wpisz rozwiązanie tutaj

Dodaj informację o porze posiłku za pomocą koloru punktów.

In [35]:
# Wpisz rozwiązanie tutaj

**Zadanie 21.** Przedstaw tę samą zależność wraz z linią regresji.

In [36]:
# Wpisz rozwiązanie tutaj

## 13. Porównywanie grup

**Zadanie 22.** Porównaj rozkład procentowego napiwku pomiędzy dniami tygodnia za pomocą wykresu pudełkowego.

In [37]:
# Wpisz rozwiązanie tutaj

**Zadanie 23.** Przedstaw liczbę rachunków w poszczególnych dniach tygodnia z podziałem na porę posiłku.

In [38]:
# Wpisz rozwiązanie tutaj

## 14. Korelacje

**Zadanie 24.** Wybierz zmienne numeryczne i oblicz ich macierz korelacji.

In [39]:
# Wpisz rozwiązanie tutaj

Przedstaw macierz korelacji na mapie cieplnej.

In [40]:
# Wpisz rozwiązanie tutaj

## 15. Mini-analiza podsumowująca

Wykonaj samodzielnie poniższe polecenia:

1. W którym dniu występuje najwięcej rachunków?
2. W którym dniu średnia wartość rachunku jest największa?
3. Którego dnia średni procent napiwku jest największy?
4. Czy większe stoliki generują większe rachunki?
5. Czy większe stoliki zostawiają większy procent napiwku?
6. Czy średni procent napiwku różni się między lunchem a kolacją?
7. Znajdź 5 rachunków z najwyższym procentowym napiwkiem.
8. Przedstaw na odpowiednim wykresie zależność między wielkością stolika a wartością rachunku.
9. Sformułuj trzy krótkie wnioski na podstawie analizy.

In [41]:
# Wpisz rozwiązanie tutaj

## Podsumowanie

Po wykonaniu projektu zapisz trzy najważniejsze rzeczy, których nauczyłeś/nauczyłaś się podczas analizy.

1. 
2. 
3.